add wave -position end  sim:/testbench/dut/arm/clk
add wave -position end  sim:/testbench/dut/arm/Instr
add wave -position end  sim:/testbench/dut/arm/ALUResult
add wave -position 2  sim:/testbench/dut/arm/ALUFlags
add wave -position 3  sim:/testbench/dut/arm/ALUControl
add wave -position end  sim:/testbench/dut/arm/dp/rf/rf
add wave -position 5  sim:/testbench/dut/arm/dp/rf/r15
add wave -position 6  sim:/testbench/dut/arm/dp/alu/a
add wave -position 7  sim:/testbench/dut/arm/dp/alu/b